<?php
/**
 * General layout for juriansluiman.nl
 */
if (!isset($locale)) {
    $locale = Locale::getDefault();
}
if (!isset($pagetype)) {
    $pagetype = 'WebPage';
}
?>
<?= $this->doctype(); ?>

<html lang="<?= Locale::getPrimaryLanguage($locale)?>">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle()->setSeparator(' &middot; ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->appendName('copyright', 'Elise Sluiman 2009-2013')
                         ->appendName('generator', 'Ensemble CMF - Soflomo.com')
                         ->appendName('viewport', 'width=device-width, initial-scale=1')
                         ?>

    <?= $this->headLink()->prependStylesheet('//fast.fonts.net/cssapi/36620992-14f0-4ddb-91fb-f0f85808413d.css')
                         ->appendStylesheet($this->basePath() . '/styles/css/styles.css?' . $this->version())
                         ?>

    <?= $this->headScript() ?>
</head>

<body itemscope itemtype="http://schema.org/<?= $pagetype?>">
    <section class="wrapper">
      <main role="main" id="content"><?= $this->content ?></main>
    </section>

    <?= $this->inlineScript()->appendScript("WebFontConfig = {
  google: { families: [ 'Source Code Pro' ] }
};

(function() {
  var wf = document.createElement('script');
  wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
           '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';

  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(wf, s);
})();") ?>
</body>
</html>
